### ISSUE TITLE
Doc link on Sylvester site broken

### ISSUE THREAD

**Issue by jewelsjacobs** [jcoglan/sylvester#18]
Just a heads up on the http://sylvester.jcoglan.com Sylvester site the link you have for the documentation (http://sylvester.jcoglan.com/docs) is broken.

Thanks for an awesome script!

**Comment by jcoglan** [comment]
This is fixed; sorry it took so long. It was awkward to deploy the site; I had to fork of `master` to get a version that would still build, but with the 0.2 docs removed.
